name: Web Tests
on:
  push:
    branches: [ "master" ]
    paths:
      - "web/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "web/**"

jobs:
  web-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./web
      - name: Lint
        run: npx nx run-many --target=lint
        working-directory: ./web

  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./web
      - name: Build
        run: npx nx run-many --target=build
        working-directory: ./web

  web-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./web
      - name: Build
        run: npx nx run-many --target=test
        working-directory: ./web

  pylint:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No check required"'
  mypy:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No check required"'
  py-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
        postgres-version: [13-bullseye]
    steps:
      - run: 'echo "No check required"'
  py-format:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No check required"'
  app-build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No check required"'
  app-lint:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No check required"'
  app-test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No check required"'